### ISSUE TITLE
Clarifying Lite and Full Edition

### ISSUE THREAD

**Issue by sunjam** [sv1sjp/NextCloudTalkAutomationBot#1]
Could you clarify what you mean by Full and Lite Edition.  Is one version paid or similar?
Thanks.

**Comment by sv1sjp** [comment]
Hey @sunjam , both versions are available for free on this repository:

* [nextcloudtalkbot_lite.py](https://github.com/sv1sjp/NextCloudTalkAutomationBot/releases/download/1.03/nextcloudtalkbot_lite.py) is the Lite Version
* [nextcloudtalkbot.py](https://github.com/sv1sjp/NextCloudTalkAutomationBot/releases/download/1.03/nextcloudtalkbot.py) is the Full Version.
